#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QECReg.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qec_0")]
	public partial class QECDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_actcode(t_actcode instance);
    partial void Updatet_actcode(t_actcode instance);
    partial void Deletet_actcode(t_actcode instance);
    partial void Insertt_user(t_user instance);
    partial void Updatet_user(t_user instance);
    partial void Deletet_user(t_user instance);
    partial void Insertt_testuser(t_testuser instance);
    partial void Updatet_testuser(t_testuser instance);
    partial void Deletet_testuser(t_testuser instance);
    #endregion
		
		public QECDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["qec_0ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QECDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QECDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QECDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QECDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_actcode> t_actcode
		{
			get
			{
				return this.GetTable<t_actcode>();
			}
		}
		
		public System.Data.Linq.Table<t_user> t_user
		{
			get
			{
				return this.GetTable<t_user>();
			}
		}
		
		public System.Data.Linq.Table<t_testuser> t_testuser
		{
			get
			{
				return this.GetTable<t_testuser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_actcode")]
	public partial class t_actcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _actcode;
		
		private System.Nullable<int> _groupid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnactcodeChanging(string value);
    partial void OnactcodeChanged();
    partial void OngroupidChanging(System.Nullable<int> value);
    partial void OngroupidChanged();
    #endregion
		
		public t_actcode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string actcode
		{
			get
			{
				return this._actcode;
			}
			set
			{
				if ((this._actcode != value))
				{
					this.OnactcodeChanging(value);
					this.SendPropertyChanging();
					this._actcode = value;
					this.SendPropertyChanged("actcode");
					this.OnactcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupid", DbType="Int")]
		public System.Nullable<int> groupid
		{
			get
			{
				return this._groupid;
			}
			set
			{
				if ((this._groupid != value))
				{
					this.OngroupidChanging(value);
					this.SendPropertyChanging();
					this._groupid = value;
					this.SendPropertyChanged("groupid");
					this.OngroupidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_user")]
	public partial class t_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _user_pass;
		
		private string _user_salt;
		
		private int _curr_ser;
		
		private System.DateTime _reg_time;
		
		private System.DateTime _last_login;
		
		private string _email;
		
		private string _qq;
		
		private string _phone;
		
		private string _realname;
		
		private string _shenfenzheng;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    partial void Onuser_saltChanging(string value);
    partial void Onuser_saltChanged();
    partial void Oncurr_serChanging(int value);
    partial void Oncurr_serChanged();
    partial void Onreg_timeChanging(System.DateTime value);
    partial void Onreg_timeChanged();
    partial void Onlast_loginChanging(System.DateTime value);
    partial void Onlast_loginChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnqqChanging(string value);
    partial void OnqqChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnrealnameChanging(string value);
    partial void OnrealnameChanged();
    partial void OnshenfenzhengChanging(string value);
    partial void OnshenfenzhengChanged();
    #endregion
		
		public t_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_salt", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_salt
		{
			get
			{
				return this._user_salt;
			}
			set
			{
				if ((this._user_salt != value))
				{
					this.Onuser_saltChanging(value);
					this.SendPropertyChanging();
					this._user_salt = value;
					this.SendPropertyChanged("user_salt");
					this.Onuser_saltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curr_ser", DbType="Int NOT NULL")]
		public int curr_ser
		{
			get
			{
				return this._curr_ser;
			}
			set
			{
				if ((this._curr_ser != value))
				{
					this.Oncurr_serChanging(value);
					this.SendPropertyChanging();
					this._curr_ser = value;
					this.SendPropertyChanged("curr_ser");
					this.Oncurr_serChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_time", DbType="DateTime NOT NULL")]
		public System.DateTime reg_time
		{
			get
			{
				return this._reg_time;
			}
			set
			{
				if ((this._reg_time != value))
				{
					this.Onreg_timeChanging(value);
					this.SendPropertyChanging();
					this._reg_time = value;
					this.SendPropertyChanged("reg_time");
					this.Onreg_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login", DbType="DateTime NOT NULL")]
		public System.DateTime last_login
		{
			get
			{
				return this._last_login;
			}
			set
			{
				if ((this._last_login != value))
				{
					this.Onlast_loginChanging(value);
					this.SendPropertyChanging();
					this._last_login = value;
					this.SendPropertyChanged("last_login");
					this.Onlast_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qq", DbType="VarChar(50)")]
		public string qq
		{
			get
			{
				return this._qq;
			}
			set
			{
				if ((this._qq != value))
				{
					this.OnqqChanging(value);
					this.SendPropertyChanging();
					this._qq = value;
					this.SendPropertyChanged("qq");
					this.OnqqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_realname", DbType="VarChar(200)")]
		public string realname
		{
			get
			{
				return this._realname;
			}
			set
			{
				if ((this._realname != value))
				{
					this.OnrealnameChanging(value);
					this.SendPropertyChanging();
					this._realname = value;
					this.SendPropertyChanged("realname");
					this.OnrealnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shenfenzheng", DbType="VarChar(50)")]
		public string shenfenzheng
		{
			get
			{
				return this._shenfenzheng;
			}
			set
			{
				if ((this._shenfenzheng != value))
				{
					this.OnshenfenzhengChanging(value);
					this.SendPropertyChanging();
					this._shenfenzheng = value;
					this.SendPropertyChanged("shenfenzheng");
					this.OnshenfenzhengChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_testuser")]
	public partial class t_testuser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private int _groupid;
		
		private int _gifttimes;
		
		private string _kodname;
		
		private string _code;
		
		private System.Nullable<System.DateTime> _reg_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OngroupidChanging(int value);
    partial void OngroupidChanged();
    partial void OngifttimesChanging(int value);
    partial void OngifttimesChanged();
    partial void OnkodnameChanging(string value);
    partial void OnkodnameChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onreg_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onreg_timeChanged();
    #endregion
		
		public t_testuser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupid", DbType="Int NOT NULL")]
		public int groupid
		{
			get
			{
				return this._groupid;
			}
			set
			{
				if ((this._groupid != value))
				{
					this.OngroupidChanging(value);
					this.SendPropertyChanging();
					this._groupid = value;
					this.SendPropertyChanged("groupid");
					this.OngroupidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gifttimes", DbType="Int NOT NULL")]
		public int gifttimes
		{
			get
			{
				return this._gifttimes;
			}
			set
			{
				if ((this._gifttimes != value))
				{
					this.OngifttimesChanging(value);
					this.SendPropertyChanging();
					this._gifttimes = value;
					this.SendPropertyChanged("gifttimes");
					this.OngifttimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodname", DbType="VarChar(200)")]
		public string kodname
		{
			get
			{
				return this._kodname;
			}
			set
			{
				if ((this._kodname != value))
				{
					this.OnkodnameChanging(value);
					this.SendPropertyChanging();
					this._kodname = value;
					this.SendPropertyChanged("kodname");
					this.OnkodnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> reg_time
		{
			get
			{
				return this._reg_time;
			}
			set
			{
				if ((this._reg_time != value))
				{
					this.Onreg_timeChanging(value);
					this.SendPropertyChanging();
					this._reg_time = value;
					this.SendPropertyChanged("reg_time");
					this.Onreg_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
